### ISSUE TITLE
Cannot start meteor, Error: Broken symbolic link encountered

### ISSUE THREAD

**Issue by rioadrian** [jeescu/meteor-react-admin-lte#5]
Hi John,

First of all I want to thank You for create this boilerplate. I've already upgrade meteor to 2.3 but now after run meteor the project won't start with error message:
```
Error: Broken symbolic link encountered at /Users/rio/Documents/git/datacenter/node_modules/.bin/detect-libc
    at isWithinProdPackage (/tools/isobuild/bundler.js:497:19)
    at /tools/isobuild/builder.js:724:15
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at Builder._copyDirectory (/tools/isobuild/builder.js:788:5)
    at Builder.copyNodeModulesDirectory (/tools/isobuild/builder.js:550:17)
    at /tools/isobuild/bundler.js:2544:17
    at Function.each (/Users/rio/.meteor/packages/meteor-tool/.2.3.2.1pb3ix4.tmajf++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore-node-f-pre.js:1321:7)
    at JsImage.write (/tools/isobuild/bundler.js:2501:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2756:13)
    at /tools/isobuild/bundler.js:2923:30
    at /tools/isobuild/bundler.js:3062:11
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3057:26
    at /tools/isobuild/bundler.js:3423:22
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3236:31)
    at /tools/isobuild/bundler.js:3179:32
    at Slot.withValue (/Users/rio/.meteor/packages/meteor-tool/.2.3.2.1pb3ix4.tmajf++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.esm.js:69:29)
    at Object.withCache (/Users/rio/.meteor/packages/meteor-tool/.2.3.2.1pb3ix4.tmajf++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1662:39)
    at Object.bundle (/tools/isobuild/bundler.js:3179:16)
    at /tools/runners/run-app.js:590:24
    at Function.run (/Users/rio/.meteor/packages/meteor-tool/.2.3.2.1pb3ix4.tmajf++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:589:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:636:35)
    at AppRunner._fiber (/tools/runners/run-app.js:958:28)
    at /tools/runners/run-app.js:419:12
```
I'v tried to googling and find out what's going on but nothing can help, so I put this aas an issue and really hopes that You can help figure it out. Thanks in advance

**Comment by delki8** [comment]
Working for me after deleting `node_modules` and running `meteor yarn install`

**Comment by rioadrian** [comment]
Thanks for respond @delki8 I'll try Your solution. 
Regards 
Rio
